const User = require('../models/User');
const Doctor = require('../models/Doctor');
const Patient = require('../models/Patient');
const Staff = require('../models/Staff');
const { sequelize } = require('../config/db');
const { sendWelcomeEmail, sendRegistrationEmail } = require('../utils/mailSender');
const crypto = require('crypto');

// Password validation helper
const validatePassword = (password) => {
  const regex = /^(?=.*[A-Z])(?=.*\d).{6,}$/;
  return regex.test(password);
};

// @desc Register a new user
// @route POST /api/users/register
// @access Public
exports.registerUser = async (req, res) => {
  console.log('--- REGISTER ATTEMPT ---', req.body.email);
  let transaction;
  try {
    transaction = await sequelize.transaction();
    let { name, email, password, role, ...extra } = req.body;

    const isAutoGenerated = !password;
    if (isAutoGenerated) {
       password = crypto.randomBytes(4).toString('hex').toUpperCase() + '$1a'; 
    }

    if (!validatePassword(password)) {
      await transaction.rollback();
      return res.status(400).json({ message: 'Password must contain at least one capital letter and one number.' });
    }

    const userExists = await User.findOne({ where: { email } });
    if (userExists) {
      await transaction.rollback();
      return res.status(400).json({ message: 'User already exists' });
    }

    const user = await User.create({ name, email, password, role }, { transaction });

    if (role === 'doctor') {
      await Doctor.create({
        userId: user.id,
        specialization: extra.specialization || 'General',
        licenseNumber: extra.licenseNumber || null,
        phone: extra.phone || null,
        experienceYears: parseInt(extra.experienceYears) || 0,
        opdFees: parseFloat(extra.opdFees) || 0
      }, { transaction });
    }

    if (role === 'user') {
      await Patient.create({
        userId: user.id,
        age: extra.age || 0,
        gender: (extra.gender || 'other').toLowerCase(),
        phone: extra.phone || null,
        address: extra.address || null,
        bloodGroup: extra.bloodGroup || null
      }, { transaction });
    }

    if (role === "staff") {
        await Staff.create({
            userId: user.id,
            staffRole: extra.staffRole || extra.role || "Receptionist",
            shift: extra.shift || "Morning",
            department: extra.department || "General",
            phone: extra.phone || null
        }, { transaction });
    }

    await transaction.commit();

    // Send professional welcome email based on registration type
    if (isAutoGenerated) {
      await sendWelcomeEmail(user.email, user.name, user.role, password);
    } else {
      await sendRegistrationEmail(user.email, user.name);
    }

    res.status(201).json({
      success: true,
      message: 'User registered successfully',
      autoPassword: isAutoGenerated ? password : null,
      data: {
        id: user.id,
        name: user.name,
        email: user.email,
        role: user.role
      }
    });
  } catch (error) {
    if (transaction) await transaction.rollback();
    console.error('Registration Error Full Log:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

// @desc Login user
// @route POST /api/users/login
// @access Public
exports.loginUser = async (req, res) => {
  try {
    const { email, password } = req.body;
    console.log(`Login attempt for: ${email}`);

    // Find user
    const user = await User.findOne({ where: { email } });

    if (!user || user.password !== password) {
      return res.status(401).json({ message: 'Invalid email or password' });
    }

    console.log(`Login successful for ${email}, Role: ${user.role}`);

    const roleRoutes = {
      admin: "/admin/dashboard",
      doctor: "/doctor/dashboard",
      staff: "/staff/dashboard",
      user: "/user/dashboard"
    };

    res.status(200).json({
      success: true,
      message: 'Login successful',
      redirectUrl: roleRoutes[user.role],
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        role: user.role
      }
    });
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

// @desc Get all users
// @route GET /api/users
// @access Private/Admin
exports.getUsers = async (req, res) => {
    try {
        const users = await User.findAll({
            order: [['createdAt', 'DESC']]
        });
        res.status(200).json({
            success: true,
            data: users
        });
    } catch (error) {
        res.status(500).json({ message: 'Server error', error: error.message });
    }
};

// @desc Get doctors
// @route GET /api/users/doctors
exports.getDoctors = async (req, res) => {
    try {
        const doctors = await User.findAll({
            where: { role: 'doctor' },
            include: [{ model: Doctor }]
        });
        res.status(200).json({
            success: true,
            data: doctors
        });
    } catch (error) {
        res.status(500).json({ message: 'Server error', error: error.message });
    }
};

// @desc Get patients
// @route GET /api/users/patients
exports.getPatients = async (req, res) => {
    try {
        const patients = await User.findAll({
            where: { role: 'user' },
            include: [{ model: Patient }]
        });
        res.status(200).json({
            success: true,
            data: patients
        });
    } catch (error) {
        res.status(500).json({ message: 'Server error', error: error.message });
    }
};

// @desc Get staff
// @route GET /api/users/staff
exports.getStaff = async (req, res) => {
    try {
        const staff = await User.findAll({
            where: { role: 'staff' },
            include: [{ model: Staff }]
        });
        res.status(200).json({
            success: true,
            data: staff
        });
    } catch (error) {
        res.status(500).json({ message: 'Server error', error: error.message });
    }
};

// @desc Update a user
// @route PUT /api/users/:id
exports.updateUser = async (req, res) => {
  try {
    const { id } = req.params;
    const { name, email, role } = req.body;

    const user = await User.findByPk(id);
    if (!user) {
      return res.status(404).json({ message: 'User not found' });
    }

    user.name = name || user.name;
    user.email = email || user.email;
    user.role = role || user.role;

    await user.save();

    res.status(200).json({ success: true, message: 'User updated successfully', data: user });
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

// @desc Delete a user
// @route DELETE /api/users/:id
exports.deleteUser = async (req, res) => {
  try {
    const { id } = req.params;
    const user = await User.findByPk(id);

    if (!user) {
      return res.status(404).json({ message: 'User not found' });
    }

    await user.destroy();
    res.status(200).json({ success: true, message: 'User deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

// @desc Get dashboard stats
// @route GET /api/users/dashboard/stats
exports.getDashboardStats = async (req, res) => {
    try {
        const { role, userId } = req.query;
        const { Op } = require('sequelize');
        const Appointment = require('../models/Appointment');

        const today = new Date().toISOString().split('T')[0];
        const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];

        // Base counts for Admin
        const [totalPatients, totalDoctors, totalStaff, totalUsers] = await Promise.all([
            User.count({ where: { role: 'user' } }),
            User.count({ where: { role: 'doctor' } }),
            User.count({ where: { role: 'staff' } }),
            User.count()
        ]);

        const totalAppointments = await Appointment.count().catch(() => 0);

        // Build weekly chart data (last 7 days)
        const weekDays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
        const weeklyData = [];
        for (let i = 6; i >= 0; i--) {
            const d = new Date(Date.now() - i * 86400000);
            const dateStr = d.toISOString().split('T')[0];
            const count = await Appointment.count({ where: { date: dateStr } }).catch(() => 0);
            weeklyData.push({ name: weekDays[d.getDay()], count });
        }

        let stats = {
            totalPatients,
            totalDoctors,
            totalStaff,
            totalUsers,
            totalAppointments,
            revenueToday: totalAppointments * 500,
            weeklyData
        };

        // Role-based filtering for stats
        if (role === 'doctor' && userId) {
            const [myToday, myTomorrow, myCompleted, myTotalPatients] = await Promise.all([
                Appointment.count({ where: { doctorId: userId, date: today } }).catch(() => 0),
                Appointment.count({ where: { doctorId: userId, date: tomorrow } }).catch(() => 0),
                Appointment.count({ where: { doctorId: userId, status: 'completed' } }).catch(() => 0),
                Appointment.count({ where: { doctorId: userId }, distinct: true, col: 'patientId' }).catch(() => 0)
            ]);
            stats.myAppointmentsToday = myToday;
            stats.myTomorrow = myTomorrow;
            stats.myCompleted = myCompleted;
            stats.myTotalPatients = myTotalPatients;
            // Progress: completed vs total today
            stats.myProgress = myToday > 0 ? Math.round((myCompleted / myToday) * 100) : 0;
        } else if (role === 'user' && userId) {
            const myAppointments = await Appointment.findAll({
                where: { patientId: userId },
                order: [['date', 'DESC']],
                limit: 1
            }).catch(() => []);
            stats.myUpcomingAppointments = await Appointment.count({ where: { patientId: userId } }).catch(() => 0);
            stats.myPrescriptionsCount = 0;
            stats.lastVisit = myAppointments.length > 0 ? myAppointments[0].date : null;
        }

        res.status(200).json({ success: true, data: stats });
    } catch (error) {
        res.status(500).json({ success: false, message: 'Failed to fetch stats', error: error.message });
    }
};

module.exports = {
    ...exports
};
